"""empty message

Revision ID: fe2ad3e3167c
Revises: 6c3a4ae32e0a
Create Date: 2022-08-16 08:49:23.079182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2ad3e3167c'
down_revision = '6c3a4ae32e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('shows', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'shows', 'Venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.drop_column('shows', 'artist_id')
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
